/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <string.h>
#include "stm32f103x.h"
#include "CAN.h"
#include "can_test.h"

uint16_t id_16_bit_id_list[] = {0x30,0x35,0x37,0x39};
uint16_t id_16_bit_id_mask[] = {0x45,0x57};
uint32_t mask_16_bit_id_mask[] = {0xAB000000,0xAB000000};

int main(void)
{
	uint32_t temp = 0;
	clock_init();
	io_init();
	uart_x_configure_parameter(&usart_2_handle);
	usart_init(&usart_2_handle);
	systick_init();

	//test_can_filter_32_bit_id_list_mode(FILTER_14,0x27,0x00,FILTER_ASSIGN_TO_FIFO_0,STANDARD_FRAME,DATA_FRAME);

	//test_can_filter_32_bit_id_list_mode(FILTER_14,0x27,0x00,FILTER_ASSIGN_TO_FIFO_0,EXTENDED_FRAME,DATA_FRAME);//test_can_btr(CAN1,250000,0x1C0001);

	//test_can_filter_32_bit_id_mask_mode(FILTER_1,0x27,0x00,FILTER_ASSIGN_TO_FIFO_0,STANDARD_FRAME,DATA_FRAME);

	//test_can_filter_16_bit_id_list_mode(FILTER_14,id_16_bit_id_list,FILTER_ASSIGN_TO_FIFO_0,DATA_FRAME);

	//test_can_filter_16_bit_id_mask_mode(FILTER_1,id_16_bit_id_mask,mask_16_bit_id_mask,FILTER_ASSIGN_TO_FIFO_0,DATA_FRAME);

	//test_can_btr(CAN1,500000,0x1C0000);

	//test_can_btr(CAN1,100000,0x1C0004);

	test_can_loopback_mode(CAN1);

	while(1)
	{
		if (counter_led_toggle >= 1000)
		{
			counter_led_toggle = 0;
			LED_TOGGLE();
		}

	}

}




