/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdio.h>
#include <string.h>
#include "stm32f103x.h"
#include "app.h"


uint8_t temp;
uint8_t i = 0;


#define HIGH 1
#define LOW  0
#define LED_ON() 			io_set_out(IO_TEST_LED, HIGH)
#define LED_OFF() 			io_set_out(IO_TEST_LED, LOW)
#define LED_TOGGLE()        io_toggle(IO_TEST_LED)



int main(void)
{
	float temp = 100.0;
	uint8_t i = 0;
	mcu_init();

	uint32_t base_addr = SCB->VTOR;
	print_msg("Base Addr: %x \r\n",base_addr);
	register_rx0_callback(app_rx0_handler);
	register_uart_callback(app_uart_rx_handler);

	//sprintf(tx_buffer_data,"EMBEDDED");
	//hal_can_transmit(CAN1,&tx_buffer_data,8,0,0,0x2A);
	//for(uint32_t i = 0; i < 100000;i++);
	//usart_read_interrupt(&usart_2_handle,rx_buffer_data,5);
	while(1)
	{
////		if (io_get_in(PUSH_BUTTON) == LOW)
////		{
////			print_msg("interrupt_count: %d \r\n",count_interrupt_enterred);
////			print_msg("ovr_count: %d \r\n",count_ovr);
////			for (i = 0; i < 6;i++)
////			{
////				print_msg("len:%d %d \r\n",i,arr_length[i]);
////			}
////
////		}
//		LED_OFF();
//		for(uint32_t i = 0; i < 1000000;i++);
//		LED_ON();
//		usart_read(&usart_2_handle,rx_buffer_data,5,100000);
//		for (uint8_t i = 0; i < 5;i++)
//		{
//			print_msg("received data:%d \r\n",rx_buffer_data[i]);
//		}

		if (counter_led_toggle >= 1000)
		{
			counter_led_toggle = 0;
			LED_TOGGLE();
		}
	}

}




